#!/bin/bash

# ==============================================================================
# Proxmox LXC to VM Converter v2
# Author: Generated by AI
# Target OS: Debian/Ubuntu based LXCs
# Improvements: Auto-dependency install, better cleanup, error trapping
# ==============================================================================

set -e

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "Please run as root"
    exit
fi

# ==============================================================================
# 0. HELPER FUNCTIONS
# ==============================================================================

# Function to check and auto-install dependencies
ensure_dependency() {
    PKG=$1
    if ! command -v $PKG >/dev/null 2>&1; then
        echo "[!] Dependency '$PKG' is missing. Attempting to install..."
        apt-get update -qq && apt-get install -y $PKG
        
        # Check again
        if ! command -v $PKG >/dev/null 2>&1; then
            echo "Error: Failed to install '$PKG'. Please install manually: apt install $PKG"
            exit 1
        fi
        echo "[OK] '$PKG' installed successfully."
    fi
}

# Function to clean up mounts/loops on exit or error
cleanup() {
    echo ""
    echo "[*] Cleaning up resources..."
    
    # Unmount chroot binds (lazy unmount to force it)
    umount -lf "$MOUNT_POINT/dev/pts" 2>/dev/null || true
    umount -lf "$MOUNT_POINT/dev" 2>/dev/null || true
    umount -lf "$MOUNT_POINT/proc" 2>/dev/null || true
    umount -lf "$MOUNT_POINT/sys" 2>/dev/null || true
    
    # Unmount main mount
    umount -lf "$MOUNT_POINT" 2>/dev/null || true
    
    # Unmount LXC if still mounted
    if [ ! -z "$CTID" ]; then pct unmount $CTID 2>/dev/null || true; fi

    # Detach loop device
    if [ ! -z "$LOOP_DEV" ]; then 
        kpartx -d $LOOP_DEV 2>/dev/null || true
        losetup -d $LOOP_DEV 2>/dev/null || true
    fi

    # Remove temp files
    if [ -d "$TEMP_DIR" ]; then
        echo "[*] Removing temporary directory: $TEMP_DIR"
        rm -rf "$TEMP_DIR"
    fi
}

# Register the cleanup trap
trap cleanup EXIT INT TERM

# ==============================================================================
# 1. SETUP & CHECKS
# ==============================================================================

echo "=========================================="
echo "    PROXMOX LXC TO VM CONVERTER v2"
echo "=========================================="

# Check Dependencies
ensure_dependency parted
ensure_dependency kpartx

# User Input
read -p "Enter Source Container ID (e.g., 100): " CTID
read -p "Enter New VM ID (e.g., 200): " VMID
read -p "Enter Target Storage Name (e.g., local-lvm): " STORAGE
read -p "Enter Disk Size in GB (must be > than used space, e.g., 32): " DISK_SIZE

# Validation
if ! pct config $CTID >/dev/null 2>&1; then
    echo "Error: Container $CTID does not exist."
    exit 1
fi

if qm config $VMID >/dev/null 2>&1; then
    echo "Error: VM ID $VMID already exists."
    exit 1
fi

TEMP_DIR="/var/lib/vz/dump/lxc-to-vm-$CTID"
IMAGE_FILE="$TEMP_DIR/disk.raw"
MOUNT_POINT="$TEMP_DIR/mnt"

# Create Workspace
rm -rf $TEMP_DIR # Ensure clean start
mkdir -p $MOUNT_POINT

# ==============================================================================
# 2. DISK CREATION
# ==============================================================================

echo "[*] Creating virtual disk image (${DISK_SIZE}GB)..."
truncate -s "${DISK_SIZE}G" $IMAGE_FILE

echo "[*] Partitioning disk (MBR/BIOS)..."
parted -s $IMAGE_FILE mklabel msdos
parted -s $IMAGE_FILE mkpart primary ext4 1MiB 100%
parted -s $IMAGE_FILE set 1 boot on

# Map loop device
LOOP_DEV=$(losetup --show -f $IMAGE_FILE)
# Map partitions
kpartx -a $LOOP_DEV
LOOP_MAP="/dev/mapper/$(basename $LOOP_DEV)p1"

# Wait a moment for device to appear
sleep 1

# Format
echo "[*] Formatting partition ($LOOP_MAP)..."
mkfs.ext4 -F $LOOP_MAP > /dev/null

# Mount
mount $LOOP_MAP $MOUNT_POINT

# ==============================================================================
# 3. DATA COPY
# ==============================================================================

echo "[*] Mounting LXC Container..."
pct mount $CTID
LXC_ROOT_MOUNT="/var/lib/lxc/$CTID/rootfs"

echo "[*] Copying filesystem (this may take time)..."
# Using rsync with specific excludes
rsync -axHAX --info=progress2 --exclude '/dev/*' --exclude '/proc/*' --exclude '/sys/*' --exclude '/tmp/*' --exclude '/run/*' --exclude '/mnt/*' --exclude '/media/*' --exclude '/lost+found' $LXC_ROOT_MOUNT/ $MOUNT_POINT/

echo "[*] Unmounting LXC..."
pct unmount $CTID

# ==============================================================================
# 4. BOOTLOADER INJECTION (CHROOT)
# ==============================================================================

echo "[*] Preparing for Bootloader Injection..."

# Bind mount system directories
mount --bind /dev $MOUNT_POINT/dev
mount --bind /dev/pts $MOUNT_POINT/dev/pts  # Added to fix apt terminal errors
mount --bind /proc $MOUNT_POINT/proc
mount --bind /sys $MOUNT_POINT/sys

# Get UUID of new partition
NEW_UUID=$(blkid -s UUID -o value $LOOP_MAP)

echo "[*] Entering Chroot to install Kernel and GRUB..."

cat <<EOF | chroot $MOUNT_POINT /bin/bash
export DEBIAN_FRONTEND=noninteractive
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# 1. Update FSTAB
echo "UUID=$NEW_UUID / ext4 errors=remount-ro 0 1" > /etc/fstab

# 2. Networking Fixes
if [ -f /etc/network/interfaces ]; then
    # Ensure standard loopback exists
    if ! grep -q "auto lo" /etc/network/interfaces; then
        echo "auto lo" >> /etc/network/interfaces
        echo "iface lo inet loopback" >> /etc/network/interfaces
    fi
    
    # Add ens18 (Proxmox standard)
    echo "" >> /etc/network/interfaces
    echo "allow-hotplug ens18" >> /etc/network/interfaces
    echo "iface ens18 inet dhcp" >> /etc/network/interfaces
    
    # Disable old eth0
    sed -i 's/^auto eth0/#auto eth0/' /etc/network/interfaces
    sed -i 's/^iface eth0/#iface eth0/' /etc/network/interfaces
fi

# Ubuntu Netplan Fix
if [ -d /etc/netplan ]; then
    rm -f /etc/netplan/*.yaml
    cat > /etc/netplan/01-netcfg.yaml <<NETPLAN
network:
  version: 2
  ethernets:
    ens18:
      dhcp4: true
NETPLAN
fi

# 3. Install Kernel
apt-get update
apt-get install -y linux-image-generic systemd-sysv grub-pc || apt-get install -y linux-image-amd64 systemd-sysv grub-pc

# 4. Install GRUB
# We force install to the loop device
grub-install --target=i386-pc --recheck $LOOP_DEV
update-grub
EOF

# ==============================================================================
# 5. VM CREATION
# ==============================================================================

# Note: Cleanup trap handles unmounting here automatically before we delete files,
# but we need to unmount $MOUNT_POINT before importing the disk.

echo "[*] Unmounting image before import..."
umount -lf "$MOUNT_POINT/dev/pts" 2>/dev/null || true
umount -lf "$MOUNT_POINT/dev" 2>/dev/null || true
umount -lf "$MOUNT_POINT/proc" 2>/dev/null || true
umount -lf "$MOUNT_POINT/sys" 2>/dev/null || true
umount -lf "$MOUNT_POINT" 2>/dev/null || true
kpartx -d $LOOP_DEV
losetup -d $LOOP_DEV
LOOP_DEV="" # Clear variable so trap doesn't try to remove it again

echo "[*] Creating VM $VMID..."

# Get settings from LXC
MEMORY=$(pct config $CTID | grep memory | awk '{print $2}')
[ -z "$MEMORY" ] && MEMORY=2048
CORES=$(pct config $CTID | grep cores | awk '{print $2}')
[ -z "$CORES" ] && CORES=2

# Create VM Shell
qm create $VMID --name "converted-lxc-$CTID" --memory $MEMORY --cores $CORES --net0 virtio,bridge=vmbr0 --bios seabios --scsihw virtio-scsi-pci

# Import Disk
echo "[*] Importing disk to $STORAGE..."
qm importdisk $VMID $IMAGE_FILE $STORAGE --format qcow2

# Attach Disk
IMPORTED_DISK="$STORAGE:vm-$VMID-disk-0"
qm set $VMID --scsi0 $IMPORTED_DISK
qm set $VMID --boot c --bootdisk scsi0
qm resize $VMID scsi0 ${DISK_SIZE}G
qm set $VMID --agent enabled=1

echo "=========================================="
echo "    CONVERSION COMPLETE"
echo "=========================================="
echo "New VM ID: $VMID"
echo "Note: Networking is set to DHCP on interface 'ens18'."
echo "Please verify boot order in Proxmox GUI."